### ISSUE TITLE
Ionic build error

### ISSUE THREAD

**Issue by dagovalsusa** [EddyVerbruggen/cordova-plugin-googleplus#638]
Hello,

i have this error when i try to build ionic for ios
```
Ld /Users/***/dev/###-app/###/platforms/ios/build/emulator/###.app/### normal x86_64 (in target: ###)
    cd /Users/***/dev/###-app/###/platforms/ios
    export IPHONEOS_DEPLOYMENT_TARGET=11.0
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.4.sdk -L/Users/***/dev/###-app/###/platforms/ios/build/emulator -F/Users/***/dev/###-app/###/platforms/ios/build/emulator -F/Users/***/Library/Developer/Xcode/DerivedData/###-hffzxlcimwroyeaxxzhfntooygvc/Build/Products/Debug-iphonesimulator/FBSDKCoreKit -F/Users/***/Library/Developer/Xcode/DerivedData/###-hffzxlcimwroyeaxxzhfntooygvc/Build/Products/Debug-iphonesimulator/FBSDKLoginKit -F/Users/***/Library/Developer/Xcode/DerivedData/###-hffzxlcimwroyeaxxzhfntooygvc/Build/Products/Debug-iphonesimulator/FBSDKShareKit -F/Users/***/Library/Developer/Xcode/DerivedData/###-hffzxlcimwroyeaxxzhfntooygvc/Build/Products/Debug-iphonesimulator/GTMSessionFetcher -F/Users/***/Library/Developer/Xcode/DerivedData/###-hffzxlcimwroyeaxxzhfntooygvc/Build/Products/Debug-iphonesimulator/GoogleToolboxForMac -F/Users/***/Library/Developer/Xcode/DerivedData/###-hffzxlcimwroyeaxxzhfntooygvc/Build/Products/Debug-iphonesimulator/GoogleUtilities -F/Users/***/dev/###-app/###/platforms/ios/Pods/GoogleSignIn/Frameworks -F###/Plugins/cordova-plugin-fcm-with-dependecy-updated -F###/Plugins/cordova-plugin-fcm-with-dependecy-updated -F###/Plugins/cordova-plugin-fcm-with-dependecy-updated -F###/Plugins/cordova-plugin-fcm-with-dependecy-updated -F###/Plugins/cordova-plugin-fcm-with-dependecy-updated -F###/Plugins/cordova-plugin-fcm-with-dependecy-updated -F###/Plugins/cordova-plugin-fcm-with-dependecy-updated -F###/Plugins/cordova-plugin-fcm-with-dependecy-updated -F###/Plugins/twitter-connect-plugin -F###/Plugins/twitter-connect-plugin -F###/Plugins/twitter-connect-plugin -F###/Plugins/cordova-plugin-googleplus -F###/Plugins/cordova-plugin-googleplus -F###/Plugins/cordova-plugin-googleplus -F###/Plugins/cordova-plugin-googleplus -F###/Plugins/cordova-plugin-googleplus -F###/Plugins/cordova-plugin-googleplus -filelist /Users/***/Library/Developer/Xcode/DerivedData/###-hffzxlcimwroyeaxxzhfntooygvc/Build/Intermediates.noindex/###.build/Debug-iphonesimulator/###.build/Objects-normal/x86_64/###.LinkFileList -Xlinker -rpath -Xlinker @executable_path/Frameworks -mios-simulator-version-min=11.0 -dead_strip -Xlinker -object_path_lto -Xlinker /Users/***/Library/Developer/Xcode/DerivedData/###-hffzxlcimwroyeaxxzhfntooygvc/Build/Intermediates.noindex/###.build/Debug-iphonesimulator/###.build/Objects-normal/x86_64/###_lto.o -Xlinker -export_dynamic -Xlinker -no_deduplicate -Xlinker -objc_abi_version -Xlinker 2 -fobjc-arc -fobjc-link-runtime -ObjC -ObjC -lz -framework CoreGraphics -framework CoreText -framework FBSDKCoreKit -framework FBSDKLoginKit -framework FBSDKShareKit -framework GTMSessionFetcher -framework GoogleSignIn -framework GoogleToolboxForMac -framework GoogleUtilities -framework LocalAuthentication -framework SafariServices -framework Security -framework SystemConfiguration -weak_framework Accounts -weak_framework AudioToolbox -weak_framework CoreGraphics -weak_framework CoreLocation -weak_framework Foundation -weak_framework QuartzCore -weak_framework Security -weak_framework Social -weak_framework UIKit -Xlinker -sectcreate -Xlinker __TEXT -Xlinker __entitlements -Xlinker /Users/***/Library/Developer/Xcode/DerivedData/###-hffzxlcimwroyeaxxzhfntooygvc/Build/Intermediates.noindex/###.build/Debug-iphonesimulator/###.build/###.app-Simulated.xcent /Users/***/dev/###-app/###/platforms/ios/build/emulator/libCordova.a -weak_framework ImageIO -framework CoreLocation -framework AVFoundation -framework FirebaseAnalytics -framework FirebaseCore -framework FirebaseInstanceID -framework FirebaseMessaging -framework GoogleInterchangeUtilities -framework GoogleIPhoneUtilities -lc++ -lz -framework AddressBook -lsqlite3.0 -framework Security -framework iAd -framework SafariServices -framework AdSupport -framework CoreSpotlight -framework Fabric -framework TwitterKit -framework TwitterCore -framework QuartzCore -framework Accounts -framework Social -framework CoreData -weak_framework WebKit -weak_framework MessageUI -framework Pods_### -framework CoreTelephony -weak_framework CoreText -weak_framework SystemConfiguration -weak-lz -Xlinker -dependency_info -Xlinker /Users/***/Library/Developer/Xcode/DerivedData/###-hffzxlcimwroyeaxxzhfntooygvc/Build/Intermediates.noindex/###.build/Debug-iphonesimulator/###.build/Objects-normal/x86_64/###_dependency_info.dat -o /Users/***/dev/###-app/###/platforms/ios/build/emulator/###.app/###
Undefined symbols for architecture x86_64:
  "_GSDK_objc_lookUpClass", referenced from:
      -[GSDK_PBExtensionField initWithDescription:] in GoogleInterchangeUtilities(PBExtensionField.o)
  "_GSDK_objc_getClass", referenced from:
      -[GSDK_PBFieldDescriptor initWithFieldDescription:rootClass:] in GoogleInterchangeUtilities(PBDescriptor.o)
      +[GSDK_PBEnumDescriptor descriptorForName:] in GoogleInterchangeUtilities(PBDescriptor.o)
      -[GSDK_PBExtensionDescriptor msgClass] in GoogleInterchangeUtilities(PBDescriptor.o)
  "_OBJC_CLASS_$_GSDK_GTMLogger", referenced from:
      objc-class-ref in GoogleIPhoneUtilities(GIPReachability.o)
  "_GSDK_objc_getProtocol", referenced from:
      _GSDK_PBMessageEncodingForSelector in GoogleInterchangeUtilities(PBUtilities.o)
  "_GSDK_NSClassFromString", referenced from:
      +[FIRAAppDelegateProxy createSubclassWithObject:] in FirebaseAnalytics(FIRAAppDelegateProxy_781e57ea09d5848cf2a3ef84e00a7a34.o)
      +[FIRAnalytics maybeEnableTagManager] in FirebaseAnalytics(FIRAnalytics_8da691577e7ff85dd61e28312a5845e1.o)
      ___41+[FIRAASIdentifierManager sharedInstance]_block_invoke in FirebaseAnalytics(FIRAASIdentifierManager_013ab22f368128dd8b96b2dff26ce63e.o)
      +[FIRAMeasurement deepLinkFromUserActivity:] in FirebaseAnalytics(FIRAMeasurement_ee9930d9338fab9382502e3b9ee38196.o)
      +[FIRMessagingAnalytics logEvent:notification:] in FirebaseMessaging(FIRMessagingAnalytics_ac603adb25062e78b5f23c421b31b7bf.o)
      +[FIRMessagingAnalytics logAnalyticsEventWithOrigin:name:parameters:] in FirebaseMessaging(FIRMessagingAnalytics_ac603adb25062e78b5f23c421b31b7bf.o)
      _FCM_swizzle_willPresentNotificationWithHandler in FirebaseMessaging(FIRMessagingAppDelegateProxy_05ec8a23bc152b34db4bae70dd691002.o)
      ...
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** BUILD FAILED **


The following build commands failed:
	Ld /Users/***/dev/###-app/###/platforms/ios/build/emulator/###.app/### normal x86_64
(1 failure)
xcodebuild: Command failed with exit code 65
[ERROR] An error occurred while running subprocess cordova.
        
        cordova build ios exited with exit code 65.
        
        Re-running this command with the --verbose flag may provide more information
```

this happened after update lib to 8.0.0

this is my ionic info
```

Ionic:

   Ionic CLI                     : 5.2.6 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.8.1
   @angular-devkit/build-angular : 0.803.1
   @angular-devkit/schematics    : 8.3.1
   @angular/cli                  : 8.3.1
   @ionic/angular-toolkit        : 2.0.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : ios 5.0.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.1.1, (and 15 other plugins)

Utility:

   cordova-res : 0.6.0 
   native-run  : not installed

System:

   ios-sim : 8.0.2
   NodeJS  : v12.8.1 (/usr/local/Cellar/node/12.8.1/bin/node)
   npm     : 6.11.2
   OS      : macOS Mojave
   Xcode   : Xcode 10.3 Build version 10G8

```

this my cordova plugin list
```

branch-cordova-sdk 3.2.0 "branch-cordova-sdk"
cordova-instagram-plugin 0.5.8 "Instagram"
cordova-plugin-camera 4.1.0 "Camera"
cordova-plugin-device 2.0.3 "Device"
cordova-plugin-facebook4 6.0.0 "Facebook Connect"
cordova-plugin-fcm-with-dependecy-updated 2.4.0 "Cordova FCM Push Plugin"
cordova-plugin-file 6.0.2 "File"
cordova-plugin-globalization 1.11.0 "Globalization"
cordova-plugin-googleplus 8.0.0 "Google SignIn"
cordova-plugin-inappbrowser 3.1.1-dev "InAppBrowser"
cordova-plugin-ionic-keyboard 2.1.3 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 4.1.1 "cordova-plugin-ionic-webview"
cordova-plugin-sim 1.3.3 "SIM"
cordova-plugin-splashscreen 5.0.3 "Splashscreen"
cordova-plugin-statusbar 2.4.3 "StatusBar"
cordova-plugin-whitelist 1.3.4 "Whitelist"
cordova-plugin-x-socialsharing 5.4.7 "SocialSharing"
cordova-universal-clipboard 0.1.0 "Clipboard"
es6-promise-plugin 4.2.2 "Promise"
twitter-connect-plugin 0.6.0 "Twitter Connect"
```

Someone could help me?
Thanks

**Comment by giladrom** [comment]
Same issue here. Have been unable to resolve it so far.

**Comment by giladrom** [comment]
Update: made some progress:

Added:
  pod 'GoogleSymbolUtilities'
  pod 'GoogleToolboxForMac'

To my pod file and project, but still have this unresolved symbol, even tho the source files are present:

Undefined symbol: _OBJC_CLASS_$_GSDK_GTMLogger
